version: '3'
services:

  #PHP Service
  php:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: docker/dockerfiles/php/Dockerfile
    image: digitalocean.com/php
    container_name: freela-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: PHPSTORM
      SERVICE_TAGS: dev
        - PHP_IDE_CONFIG=serverName=PHPSTORM
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/conf/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/conf/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "5173:5173"
      - "9001:9001"
    networks:
      - freela-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: freela-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/conf/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - freela-network

  #MySQL Service
  mysql:
    image: mysql
    container_name: freela-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: freela
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - freela-network

#Docker Networks
networks:
  freela-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
